# Xray kubernetes service
apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: amazon-cloudwatch
spec:
  selector:
    name: xray-daemon
  clusterIP: None
  ports:
    - name: xray-ingest
      port: 2000
      protocol: UDP
    - name: xray-tcp
      port: 2000
      protocol: TCP